services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    user: root
    container_name: jenkins
    expose:
      - "8443"
    volumes:
      - ./jenkins_home:/var/jenkins_home:rw # << ./ 해주면 현재 디렉토리에 jenkins_home을 생성함
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    networks:
      - app_network
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
      JENKINS_OPTS: "--httpPort=8443 --prefix=/jenkins"

networks:
  app_network:
    external: true
